# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/google/cloud/datastore/datastore-v1-proto-client/1.6.0/datastore-v1-proto-client-1.6.0.jar'
  require 'io/grpc/grpc-core/1.9.0/grpc-core-1.9.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-language-v1beta2/0.6.0/proto-google-cloud-language-v1beta2-0.6.0.jar'
  require 'io/grpc/grpc-netty-shaded/1.9.0/grpc-netty-shaded-1.9.0.jar'
  require 'com/google/api/grpc/grpc-google-cloud-spanner-v1/0.6.0/grpc-google-cloud-spanner-v1-0.6.0.jar'
  require 'io/grpc/grpc-auth/1.9.0/grpc-auth-1.9.0.jar'
  require 'com/google/cloud/google-cloud-bigtable/0.41.0-alpha/google-cloud-bigtable-0.41.0-alpha.jar'
  require 'io/grpc/grpc-protobuf/1.9.0/grpc-protobuf-1.9.0.jar'
  require 'com/google/http-client/google-http-client-jackson2/1.19.0/google-http-client-jackson2-1.19.0.jar'
  require 'io/opencensus/opencensus-contrib-grpc-metrics/0.10.0/opencensus-contrib-grpc-metrics-0.10.0.jar'
  require 'com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.jar'
  require 'joda-time/joda-time/2.9.2/joda-time-2.9.2.jar'
  require 'com/google/api/grpc/grpc-google-cloud-spanner-admin-database-v1/0.6.0/grpc-google-cloud-spanner-admin-database-v1-0.6.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-spanner-v1/0.6.0/proto-google-cloud-spanner-v1-0.6.0.jar'
  require 'com/google/http-client/google-http-client/1.19.0/google-http-client-1.19.0.jar'
  require 'com/google/cloud/google-cloud-firestore/0.41.0-beta/google-cloud-firestore-0.41.0-beta.jar'
  require 'com/google/cloud/google-cloud-dialogflow/0.41.0-alpha/google-cloud-dialogflow-0.41.0-alpha.jar'
  require 'commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar'
  require 'com/google/api/grpc/proto-google-cloud-datastore-v1/0.6.0/proto-google-cloud-datastore-v1-0.6.0.jar'
  require 'com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar'
  require 'com/google/cloud/google-cloud-storage/1.23.0/google-cloud-storage-1.23.0.jar'
  require 'com/google/cloud/google-cloud-errorreporting/0.41.0-beta/google-cloud-errorreporting-0.41.0-beta.jar'
  require 'com/google/apis/google-api-services-cloudresourcemanager/v1-rev470-1.23.0/google-api-services-cloudresourcemanager-v1-rev470-1.23.0.jar'
  require 'io/grpc/grpc-stub/1.9.0/grpc-stub-1.9.0.jar'
  require 'com/google/cloud/google-cloud-translate/1.23.0/google-cloud-translate-1.23.0.jar'
  require 'com/google/cloud/google-cloud-bigquery/1.23.0/google-cloud-bigquery-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-speech-v1p1beta1/0.6.0/proto-google-cloud-speech-v1p1beta1-0.6.0.jar'
  require 'org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar'
  require 'com/google/api/grpc/proto-google-cloud-language-v1/1.5.0/proto-google-cloud-language-v1-1.5.0.jar'
  require 'com/google/auth/google-auth-library-credentials/0.9.0/google-auth-library-credentials-0.9.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-firestore-v1beta1/0.6.0/proto-google-cloud-firestore-v1beta1-0.6.0.jar'
  require 'com/google/cloud/google-cloud-core-grpc/1.23.0/google-cloud-core-grpc-1.23.0.jar'
  require 'io/opencensus/opencensus-contrib-http-util/0.11.1/opencensus-contrib-http-util-0.11.1.jar'
  require 'com/google/api/grpc/proto-google-cloud-trace-v2/0.6.0/proto-google-cloud-trace-v2-0.6.0.jar'
  require 'com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar'
  require 'com/google/guava/guava/19.0/guava-19.0.jar'
  require 'com/google/http-client/google-http-client-protobuf/1.20.0/google-http-client-protobuf-1.20.0.jar'
  require 'com/google/apis/google-api-services-storage/v1-rev114-1.23.0/google-api-services-storage-v1-rev114-1.23.0.jar'
  require 'com/google/cloud/google-cloud-vision/1.23.0/google-cloud-vision-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-vision-v1p2beta1/1.5.0/proto-google-cloud-vision-v1p2beta1-1.5.0.jar'
  require 'commons-codec/commons-codec/1.3/commons-codec-1.3.jar'
  require 'com/google/api/grpc/proto-google-cloud-spanner-admin-instance-v1/0.6.0/proto-google-cloud-spanner-admin-instance-v1-0.6.0.jar'
  require 'com/google/cloud/google-cloud-pubsub/0.41.0-beta/google-cloud-pubsub-0.41.0-beta.jar'
  require 'com/google/instrumentation/instrumentation-api/0.4.3/instrumentation-api-0.4.3.jar'
  require 'com/google/api/grpc/proto-google-cloud-vision-v1/1.5.0/proto-google-cloud-vision-v1-1.5.0.jar'
  require 'commons-fileupload/commons-fileupload/1.3.2/commons-fileupload-1.3.2.jar'
  require 'com/google/api/grpc/proto-google-cloud-bigtable-admin-v2/0.6.0/proto-google-cloud-bigtable-admin-v2-0.6.0.jar'
  require 'com/google/apis/google-api-services-bigquery/v2-rev377-1.23.0/google-api-services-bigquery-v2-rev377-1.23.0.jar'
  require 'com/google/cloud/google-cloud-datastore/1.23.0/google-cloud-datastore-1.23.0.jar'
  require 'com/google/auto/value/auto-value/1.4/auto-value-1.4.jar'
  require 'com/google/code/gson/gson/2.7/gson-2.7.jar'
  require 'io/opencensus/opencensus-contrib-grpc-util/0.11.1/opencensus-contrib-grpc-util-0.11.1.jar'
  require 'com/google/cloud/google-cloud-dns/0.41.0-alpha/google-cloud-dns-0.41.0-alpha.jar'
  require 'commons-io/commons-io/2.2/commons-io-2.2.jar'
  require 'com/google/cloud/google-cloud-speech/0.41.0-alpha/google-cloud-speech-0.41.0-alpha.jar'
  require 'io/grpc/grpc-context/1.9.0/grpc-context-1.9.0.jar'
  require 'com/google/api/gax/1.20.0/gax-1.20.0.jar'
  require 'com/google/api/grpc/grpc-google-cloud-spanner-admin-instance-v1/0.6.0/grpc-google-cloud-spanner-admin-instance-v1-0.6.0.jar'
  require 'io/opencensus/opencensus-api/0.11.1/opencensus-api-0.11.1.jar'
  require 'com/google/cloud/google-cloud-logging/1.23.0/google-cloud-logging-1.23.0.jar'
  require 'org/codehaus/jackson/jackson-core-asl/1.9.11/jackson-core-asl-1.9.11.jar'
  require 'io/grpc/grpc-protobuf-lite/1.9.0/grpc-protobuf-lite-1.9.0.jar'
  require 'com/google/apis/google-api-services-compute/v1-rev103-1.21.0/google-api-services-compute-v1-rev103-1.21.0.jar'
  require 'com/google/cloud/google-cloud-core/1.23.0/google-cloud-core-1.23.0.jar'
  require 'org/threeten/threetenbp/1.3.3/threetenbp-1.3.3.jar'
  require 'com/google/http-client/google-http-client-jackson/1.23.0/google-http-client-jackson-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-speech-v1/0.6.0/proto-google-cloud-speech-v1-0.6.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-vision-v1p1beta1/0.6.0/proto-google-cloud-vision-v1p1beta1-0.6.0.jar'
  require 'com/google/api/api-common/1.5.0/api-common-1.5.0.jar'
  require 'com/fasterxml/jackson/core/jackson-core/2.1.3/jackson-core-2.1.3.jar'
  require 'com/google/api/grpc/grpc-google-cloud-pubsub-v1/0.6.0/grpc-google-cloud-pubsub-v1-0.6.0.jar'
  require 'com/google/cloud/google-cloud-trace/0.41.0-beta/google-cloud-trace-0.41.0-beta.jar'
  require 'com/google/protobuf/protobuf-java-util/3.5.1/protobuf-java-util-3.5.1.jar'
  require 'com/google/http-client/google-http-client-appengine/1.23.0/google-http-client-appengine-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-trace-v1/0.6.0/proto-google-cloud-trace-v1-0.6.0.jar'
  require 'org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar'
  require 'com/google/api/grpc/proto-google-cloud-dialogflow-v2beta1/0.6.0/proto-google-cloud-dialogflow-v2beta1-0.6.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-monitoring-v3/0.6.0/proto-google-cloud-monitoring-v3-0.6.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-error-reporting-v1beta1/0.6.0/proto-google-cloud-error-reporting-v1beta1-0.6.0.jar'
  require 'com/google/cloud/google-cloud-monitoring/0.41.0-beta/google-cloud-monitoring-0.41.0-beta.jar'
  require 'com/google/cloud/google-cloud-spanner/0.41.0-beta/google-cloud-spanner-0.41.0-beta.jar'
  require 'com/google/api/grpc/proto-google-cloud-spanner-admin-database-v1/0.6.0/proto-google-cloud-spanner-admin-database-v1-0.6.0.jar'
  require 'com/google/oauth-client/google-oauth-client/1.23.0/google-oauth-client-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-speech-v1beta1/0.6.0/proto-google-cloud-speech-v1beta1-0.6.0.jar'
  require 'com/google/cloud/google-cloud-language/1.23.0/google-cloud-language-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-logging-v2/0.6.0/proto-google-cloud-logging-v2-0.6.0.jar'
  require 'com/google/api/grpc/proto-google-common-protos/1.5.0/proto-google-common-protos-1.5.0.jar'
  require 'com/google/cloud/google-cloud-compute/0.41.0-alpha/google-cloud-compute-0.41.0-alpha.jar'
  require 'com/google/api/grpc/grpc-google-common-protos/1.5.0/grpc-google-common-protos-1.5.0.jar'
  require 'com/google/api/grpc/proto-google-cloud-pubsub-v1/0.6.0/proto-google-cloud-pubsub-v1-0.6.0.jar'
  require 'com/google/apis/google-api-services-dns/v1-rev66-1.23.0/google-api-services-dns-v1-rev66-1.23.0.jar'
  require 'com/google/api/grpc/proto-google-iam-v1/0.6.0/proto-google-iam-v1-0.6.0.jar'
  require 'junit/junit/4.12/junit-4.12.jar'
  require 'com/google/cloud/google-cloud-core-http/1.23.0/google-cloud-core-http-1.23.0.jar'
  require 'com/google/cloud/google-cloud-resourcemanager/0.41.0-alpha/google-cloud-resourcemanager-0.41.0-alpha.jar'
  require 'com/google/api/gax-grpc/1.20.0/gax-grpc-1.20.0.jar'
  require 'org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar'
  require 'com/google/errorprone/error_prone_annotations/2.1.2/error_prone_annotations-2.1.2.jar'
  require 'com/google/api/grpc/proto-google-cloud-bigtable-v2/0.6.0/proto-google-cloud-bigtable-v2-0.6.0.jar'
  require 'com/google/api/gax-httpjson/0.37.0/gax-httpjson-0.37.0.jar'
  require 'com/google/cloud/google-cloud/0.41.0-alpha/google-cloud-0.41.0-alpha.jar'
  require 'com/google/apis/google-api-services-translate/v2-rev47-1.22.0/google-api-services-translate-v2-rev47-1.22.0.jar'
  require 'com/google/auth/google-auth-library-oauth2-http/0.9.0/google-auth-library-oauth2-http-0.9.0.jar'
end

if defined? Jars
  require_jar 'com.google.cloud.datastore', 'datastore-v1-proto-client', '1.6.0'
  require_jar 'io.grpc', 'grpc-core', '1.9.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-language-v1beta2', '0.6.0'
  require_jar 'io.grpc', 'grpc-netty-shaded', '1.9.0'
  require_jar 'com.google.api.grpc', 'grpc-google-cloud-spanner-v1', '0.6.0'
  require_jar 'io.grpc', 'grpc-auth', '1.9.0'
  require_jar 'com.google.cloud', 'google-cloud-bigtable', '0.41.0-alpha'
  require_jar 'io.grpc', 'grpc-protobuf', '1.9.0'
  require_jar 'com.google.http-client', 'google-http-client-jackson2', '1.19.0'
  require_jar 'io.opencensus', 'opencensus-contrib-grpc-metrics', '0.10.0'
  require_jar 'com.google.api-client', 'google-api-client', '1.23.0'
  require_jar 'joda-time', 'joda-time', '2.9.2'
  require_jar 'com.google.api.grpc', 'grpc-google-cloud-spanner-admin-database-v1', '0.6.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-spanner-v1', '0.6.0'
  require_jar 'com.google.http-client', 'google-http-client', '1.19.0'
  require_jar 'com.google.cloud', 'google-cloud-firestore', '0.41.0-beta'
  require_jar 'com.google.cloud', 'google-cloud-dialogflow', '0.41.0-alpha'
  require_jar 'commons-logging', 'commons-logging', '1.1.1'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-datastore-v1', '0.6.0'
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.1'
  require_jar 'com.google.cloud', 'google-cloud-storage', '1.23.0'
  require_jar 'com.google.cloud', 'google-cloud-errorreporting', '0.41.0-beta'
  require_jar 'com.google.apis', 'google-api-services-cloudresourcemanager', 'v1-rev470-1.23.0'
  require_jar 'io.grpc', 'grpc-stub', '1.9.0'
  require_jar 'com.google.cloud', 'google-cloud-translate', '1.23.0'
  require_jar 'com.google.cloud', 'google-cloud-bigquery', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-speech-v1p1beta1', '0.6.0'
  require_jar 'org.apache.httpcomponents', 'httpclient', '4.0.1'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-language-v1', '1.5.0'
  require_jar 'com.google.auth', 'google-auth-library-credentials', '0.9.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-firestore-v1beta1', '0.6.0'
  require_jar 'com.google.cloud', 'google-cloud-core-grpc', '1.23.0'
  require_jar 'io.opencensus', 'opencensus-contrib-http-util', '0.11.1'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-trace-v2', '0.6.0'
  require_jar 'com.google.protobuf', 'protobuf-java', '3.5.1'
  require_jar 'com.google.guava', 'guava', '19.0'
  require_jar 'com.google.http-client', 'google-http-client-protobuf', '1.20.0'
  require_jar 'com.google.apis', 'google-api-services-storage', 'v1-rev114-1.23.0'
  require_jar 'com.google.cloud', 'google-cloud-vision', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-vision-v1p2beta1', '1.5.0'
  require_jar 'commons-codec', 'commons-codec', '1.3'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-spanner-admin-instance-v1', '0.6.0'
  require_jar 'com.google.cloud', 'google-cloud-pubsub', '0.41.0-beta'
  require_jar 'com.google.instrumentation', 'instrumentation-api', '0.4.3'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-vision-v1', '1.5.0'
  require_jar 'commons-fileupload', 'commons-fileupload', '1.3.2'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-bigtable-admin-v2', '0.6.0'
  require_jar 'com.google.apis', 'google-api-services-bigquery', 'v2-rev377-1.23.0'
  require_jar 'com.google.cloud', 'google-cloud-datastore', '1.23.0'
  require_jar 'com.google.auto.value', 'auto-value', '1.4'
  require_jar 'com.google.code.gson', 'gson', '2.7'
  require_jar 'io.opencensus', 'opencensus-contrib-grpc-util', '0.11.1'
  require_jar 'com.google.cloud', 'google-cloud-dns', '0.41.0-alpha'
  require_jar 'commons-io', 'commons-io', '2.2'
  require_jar 'com.google.cloud', 'google-cloud-speech', '0.41.0-alpha'
  require_jar 'io.grpc', 'grpc-context', '1.9.0'
  require_jar 'com.google.api', 'gax', '1.20.0'
  require_jar 'com.google.api.grpc', 'grpc-google-cloud-spanner-admin-instance-v1', '0.6.0'
  require_jar 'io.opencensus', 'opencensus-api', '0.11.1'
  require_jar 'com.google.cloud', 'google-cloud-logging', '1.23.0'
  require_jar 'org.codehaus.jackson', 'jackson-core-asl', '1.9.11'
  require_jar 'io.grpc', 'grpc-protobuf-lite', '1.9.0'
  require_jar 'com.google.apis', 'google-api-services-compute', 'v1-rev103-1.21.0'
  require_jar 'com.google.cloud', 'google-cloud-core', '1.23.0'
  require_jar 'org.threeten', 'threetenbp', '1.3.3'
  require_jar 'com.google.http-client', 'google-http-client-jackson', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-speech-v1', '0.6.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-vision-v1p1beta1', '0.6.0'
  require_jar 'com.google.api', 'api-common', '1.5.0'
  require_jar 'com.fasterxml.jackson.core', 'jackson-core', '2.1.3'
  require_jar 'com.google.api.grpc', 'grpc-google-cloud-pubsub-v1', '0.6.0'
  require_jar 'com.google.cloud', 'google-cloud-trace', '0.41.0-beta'
  require_jar 'com.google.protobuf', 'protobuf-java-util', '3.5.1'
  require_jar 'com.google.http-client', 'google-http-client-appengine', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-trace-v1', '0.6.0'
  require_jar 'org.hamcrest', 'hamcrest-core', '1.3'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-dialogflow-v2beta1', '0.6.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-monitoring-v3', '0.6.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-error-reporting-v1beta1', '0.6.0'
  require_jar 'com.google.cloud', 'google-cloud-monitoring', '0.41.0-beta'
  require_jar 'com.google.cloud', 'google-cloud-spanner', '0.41.0-beta'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-spanner-admin-database-v1', '0.6.0'
  require_jar 'com.google.oauth-client', 'google-oauth-client', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-speech-v1beta1', '0.6.0'
  require_jar 'com.google.cloud', 'google-cloud-language', '1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-logging-v2', '0.6.0'
  require_jar 'com.google.api.grpc', 'proto-google-common-protos', '1.5.0'
  require_jar 'com.google.cloud', 'google-cloud-compute', '0.41.0-alpha'
  require_jar 'com.google.api.grpc', 'grpc-google-common-protos', '1.5.0'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-pubsub-v1', '0.6.0'
  require_jar 'com.google.apis', 'google-api-services-dns', 'v1-rev66-1.23.0'
  require_jar 'com.google.api.grpc', 'proto-google-iam-v1', '0.6.0'
  require_jar 'junit', 'junit', '4.12'
  require_jar 'com.google.cloud', 'google-cloud-core-http', '1.23.0'
  require_jar 'com.google.cloud', 'google-cloud-resourcemanager', '0.41.0-alpha'
  require_jar 'com.google.api', 'gax-grpc', '1.20.0'
  require_jar 'org.apache.httpcomponents', 'httpcore', '4.0.1'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.1.2'
  require_jar 'com.google.api.grpc', 'proto-google-cloud-bigtable-v2', '0.6.0'
  require_jar 'com.google.api', 'gax-httpjson', '0.37.0'
  require_jar 'com.google.cloud', 'google-cloud', '0.41.0-alpha'
  require_jar 'com.google.apis', 'google-api-services-translate', 'v2-rev47-1.22.0'
  require_jar 'com.google.auth', 'google-auth-library-oauth2-http', '0.9.0'
end
